# Generated by Django 2.2 on 2022-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
